export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_START = 'AUTHENTICATE_START';
export const AUTHENTICATE_FAIL = 'AUTHENTICATE_FAIL';
export const UNAUTHENTICATE = 'UNAUTHENTICATE';
